server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  data:
    redis:
      host: localhost
      port: 6379

    elasticsearch:
      username: ${elasticsearch_username}
      password: ${elasticsearch_password}
      host: localhost
      port: 9200
      fingerprint: ${elasticsearch_fingerprint}

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

jwt:
  secret-key: ${jwt_secret_key}
  issuer: ${jwt_issuer}
  access-token-expire-time: ${jwt_access_token_expired_time}
  refresh-token-expire-time: ${jwt_refresh_token_expired_time}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO

servers:
  url: "http://localhost"
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO