name: CI (feat. Java CI with Gradle)

on:
  pull_request:
    branches:
      - release # 배포
      - main # 개발

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 [temurin(Oracle)]
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 테스트를 실행을 위한 application.yml(test) 환경변수 설정
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/test/resources/application.yml
        env:
          #          spring.mail.username: ${{secrets.MAIL_USERNAME}}
          #          spring.mail.password: ${{secrets.MAIL_PASSWORD}}
          spring.mail.username: ${{secrets.MAIL_USERNAME2}}
          spring.mail.password: ${{secrets.MAIL_PASSWORD2}}
          jwt.secret-key: ${{secrets.JWT_SECRET_KEY}}
          jwt.issuer: ${{secrets.JWT_ISSUER}}
          jwt.access-token-expire-time: ${{secrets.JWT_ACCESS_TOKEN_EXPIRED_TIME}}

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle [--parallel]
        run: ./gradlew --info --parallel test
